### ISSUE TITLE
Feature request to support multiple RSS feed sources

### ISSUE THREAD

**Issue by s1-ranjan** [justoverclockl/flarum-ext-newsfeed#1]
This is a good plugin but as of now it only supports one RSS feed source, it would be nice if it can have the capability to accommodate numerous sources.

**Comment by justoverclockl** [comment]
this actually supports multiple urls, simply add url separated by comma, but u need to change the css settings, if u add 2 rss url, u will have 5 + 5 items displayed....so maybe u need to fix the css to display it correctly

![hhhh](https://user-images.githubusercontent.com/79002016/119639162-a19edb80-be17-11eb-87ea-9de6430671ed.png)

as u can see it works well but need some "style" :)

**Comment by justoverclockl** [comment]
i will close this issue, feel free to open a new one if u have more suggestion/problem
